version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: spotify_dev
    restart: always
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
